### ISSUE TITLE
HTML, CSS Template 

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#33]
#### Description: 
- Make a template HTML file which other devs will copy to start the project
- Both Paul and Ned work on the same branch
- DEADLINE: May 16th 2pm

#### TODOs HTML
- [x] create a files called 'template.html' in the 'projects/templates'  directory
- [ ] Make it access the 'template.css' file
- [ ] create standard HTML file with <style>, no dedicated header or footer, we will be using divs
- [ ] In the body, add 'div' for 'header', 'body', and 'footer'
- [ ] Add a title to the header div saying 'Jover 15' with ID 'HeaderTitle'
- [ ] Add a button to the header div with ID 'headerBtn' and text 'Home Page'
- [ ] Link Header button to ''../homePage/home_page.html"
- [ ] Add a footer div
- [ ] In the footer div, Add a button to the header with ID 'footerBtn' and text 'Feedback'
- [ ] Link Footer button to ''../feedbackPage/feedback_page.html"

#### TODO CSS: Feel free to make any artistic descisions
- [ ] create a files called 'template.css' in the 'projects/templates' directory
- [ ] Design the following ID styles according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
   - [ ] '#HeaderTitle' 
   - [ ] '#headerBtn'
   - [ ] '#footerBtn"
- [ ] Design the following classes according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
   - [ ] '.header'
   - [ ] '.footer'

Ensure that html and css templates work together
