### ISSUE TITLE
Add Home Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#34]
#### Description: 
- Create and design the HTML, CSS and JS for Home Page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```

#### First step:
- [ ] Create a directory in 'projects' called homePage

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/homePage'
- [x] Rename this file as 'home_page.html'
- [ ] Change <style> to link to  'home_page.css'
- [ ] In the body add the following
    - [ ] Create div with class 'SubHeaderHomePageDiv'
    - [ ] Within this div place the following
       - [ ] Add 'Active Projects' as text with class 'ActiveProjectsTitle'
       - [ ] Add a search box with class 'Search'
       - [ ] and a plus button to add a new project  with class 'AddProjectPlusBtn'
       - [ ] link the button to '../projects/addProjectPage/add_project_page.html'
       - [ ] Style them with CSS to fit the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
    - [ ] Create another div with class "ProjectsList"
    - [ ] Add a list with class 'projects'  
    - [ ] Add a div called 'AddProjectDiv'
       - [ ] In this DIv, add a button with class 'AddProjectBtn'
       - [ ] link the button to '../projects/addProjectPage/add_project_page.html'
    - [ ] Add a div called 'AddArchiveDiv'
       - [ ] In this Div, add a button with text 'Archive Page' with class 'ArchivePageBtn'
       - [ ] link this button to "../projects/archivePage/archive_page.html"  
 - [ ] Make each project list item has a delete logo on the right which can delete the item
 - [ ] Make each project list item have an archive button

#### TODOs CSS
- [ ] from 'projects/template', copy "template.css" to 'projects/homePage'
- [ ] Rename this file as 'home_page.css'
- [ ] Style all the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design 
     - [ ] '.SubHeaderHomePageDiv'
     - [ ] '.ActiveProjectsTitle'
     - [ ] '.Search'
     - [ ]  '.AddProjectPlusBtn'
     - [ ] ".project_list"
     - [ ] 'AddProjectDiv'
     - [ ]  '.AddProjectBtn'
     - [ ] '.AddArchiveDiv'
     - [ ] ".ArchivePageBtn"

#### TODOs Javascript
- [ ] in 'projects/', create 'home_page.js'
- [ ] Create a list of dummy projects according to the JSON format specified above and place them in localStorage
- [ ] Add javascript to make search work
- [ ] Add Javascript so that delete project functions work
    - [ ] remove that project from the localStorage
- [ ] Add Javascript so that archive project works
    - [ ] edit the project so active is set to false in localStorage
- [ ] Add js so when a project is clicked, current_project is set correclty and we are routed to "project/projectHomePage/project_home_page.html" 
- [ ] In "projects/tests" create a file called "home_page.tests.js"
- [ ] Write the following tests
   - [ ] the search function
   - [ ] Delete Project Functionality
   - [ ] Archive Functionality
   - [ ] When a project is selected, current_project is set correctly
