### ISSUE TITLE
Add New Project Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#35]
#### Description: 
- Create and design the HTML, CSS and JS for add new project page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```

#### First step:
- [x] Create a directory in 'projects' called addProjectPage

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/addProjectPage'
- [x] Rename this file as 'add_project_page.html'
- [x] Create Div called with class "addProjectFromDiv"
    - [x] Add a text box with class "projectName" 
    - [x] Add a drop_down box (come up with some categories) with  class "projectTag"  
    - [x] Add a text box with  class "projectContributor"  
    - [x] Add a text box with  class "projectDescription"  
- [x] Create Div called with class "projectSubmitDiv"
    - [x] Add a button with class "submitBtn"
    - [x] Link button to "../homePage/home_page.html"

#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/addProjectPage'
- [x] Rename this file as 'add_project_page.css'
- [x] Style the following according to the  [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
   - [x] addProjectFromDiv
   - [x] .projectNameDiv
   - [x] .projectName
   - [x] .projectTag
   - [x] .projectContributor
   - [x] .projectDescription
   - [x] .projectSubmitDiv
   - [x] .submitBtn

#### TODOs Javascript
- [x] in 'projects/addProjectPage', create 'add_project_page.js'
- [x] Add validation function for each  form submission
- [x] if not valid, alert the user for a rejection
- [x] If accepted add the project to localStorage according to the json Format
- [x] Add a file in 'project/tests' called 'add_project_page.tests.js'
    - [x] Add a test to make sure form only submits if all text entries are valid 
    - [x] Add test to make json file added to localStoarge is formatted correctly
    - [x] Add dummy submissions to localStorage and check if adding a new project through the form is accurate
