### ISSUE TITLE
Add Feedback Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#36]
#### Description: 
- Create and design the HTML, CSS and JS for Feedback
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design

#### First step:
- [x] Create a directory in 'projects' called feebackPage

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/feebackPage'
- [x] Rename this file as 'feedback_page.html'
- [x] Add a div called "sentimentWidget"
     - [x] Create a sentiment widget as per the warmup excercies
- [x] Create a div called "feedbackBtns"
     - [x] Create a submit button with class "submitBtn"
     - [x] link it to "../successPage/success_page.html"
     - [x] Create a cancel button with class "cancelBtn"
     - [x] link it to "../homePage/home_page.html"

#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/feebackPage'
- [x] Rename this file as 'feedback_page.css'
- [x] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
     - [x] sentimentWidget
     - [x] feedbackBtns
     - [x] submitBtn
     - [x] cancelBtn

#### TODOs Javascript
- [x] in 'projects/feebackPage', create 'feedback_page.js'
- [x] Add a validation for the widget where the form is only accepted if all entries are valid
- [x] if not valid, alert the user
- [x] In 'projects/tests', create a file called "feedback_page.tests.js"
    - [x] Add  test to ensure that only a valid form submission is accepted
    - [x] and invalid forms are alerted
