### ISSUE TITLE
Add New Log Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#37]
#### Description: 
- Create and design the HTML, CSS and JS for add new log page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the local storage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```

#### First step:
- [x] Create a directory in 'projects' called addLogPage

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/addLogPage'
- [x] Rename this file as 'add_log_page.html'
- [x] Create Div called with class "addLogFromDiv"
    - [x] Add a text box with class "logTitle" 
    - [x] Add a time select box (come up with some categories) with  class "logTime"  
    - [x] Add a text box with  class "logContributor"  
    - [x] Add a text box with  class "logDescription"  
- [x] Create Div called with class "logbtnsDiv"
    - [x] Add a submit button with class "submitBtn"
    - [x] Link button to "../dayPage/day_page.html"
    - [x] Add a cancel button with class "cancelBtn"
    - [x] Link button to "../dayPage/day_page.html"

#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/addLogPage'
- [x] Rename this file as 'add_log_page.css'
- [x] Style the following according to the  [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
   - [x] addLogFromDiv
   - [x] logTitle
   - [x] logTime
   - [x] logContributor
   - [x] logDescription
   - [x] logbtnsDiv
   - [x] submitBtn
   - [x] cancelBtn

#### TODOs Javascript
- [x] in 'projects/addLogPage', create 'add_log_page.js'
- [x] Add validation function for each  form submission
- [x] if not valid, alert the user for a rejection
- [x] If valid, for the project based in the 'current_project' in local storage, add a new log entry
- [x] base DD and MM and YYYY on current_date field
- [x] Add a file in 'project/tests' called 'add_log_page.tests.js'
    - [x] Add a test to make sure form only submits if all text entries are valid 
    - [x] add tests to make sure form log submission adds to localStorage
    - [x] Create dummy logs and check if form adds log submission accurately
