### ISSUE TITLE
Add Archive Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#38]
#### Description: 
- Create and design the HTML, CSS and JS for Archive
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [x] Create a directory in 'projects' called archivePage 
- [ ] The Page will present a maximum of 5 projects at once

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/archivePage'
- [x] Rename this file as 'archive_page.html'
- [x] Add a div with class "ArchivePageHeaderDiv"
    - [x] Add Archive projects text
    - [x] Add Search Bar with class "Search" 
- [x] Add a div with class "ArchiveProjectListDiv"
    - [x] Add list object with class "ProjectList"
    - [x]  Add items with class "Project"
    - [x] Add delete button trash can on the right most side
- [x] Add a div called "ArchivePageBtns"
    - [x] Add a page back button with class "pageBackBtn"
    - [x] Add a next page button with class "pageNextBtn"
   

#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/archivePage'
- [x] Rename this file as 'archive_page.css'
- [x] Design the following from the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
    - [x] ArchivePageHeaderDiv
    - [x] Search
    - [x] ArchiveProjectListDiv
    - [x] ProjectList
    - [x] Project"
    - [x] ArchivePageBtns
    - [x] pageBackBtn
    - [x] pageNextBtn

#### TODOs Javascript
- [x] in 'projects/archivePage', create 'archive_page.js'
- [x] Add Search functionality from data in localStorage
- [x] From localStorage, pull out all active: false projects and place them in Session Storage
- [x] Decorate page with a maximum of 5 projects all from SessionStorage which contains active: false
- [x] Set page back and forth to move back and forth accordingly
- [x] If a project is clicked, set current_project: to project_n and route to link "../projects/projectHomePage/project_home_page.html"
- [x] In project/tests folder create a file called "archive_page.tests.js"
- [x] Add the following tests
     - [x] All archived projects are correctly loaded
     - [x] page back works correctly
     - [x] page next works correctly
     - [x] Search Works correctly
     - [x] Delete works correctly
     - [x] when a project is pressed, current_project in localStorage is set correctly
