### ISSUE TITLE
Add Success Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#39]
#### Description: 
- Create and design the HTML, CSS and JS for Success Page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [x] Create a directory in 'projects' called successPage

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/successPage'
- [x] Rename this file as 'success_page.html'
- [x] Add a div called "SuccessPageTextDiv"
    - [x] Add text "Thank you for you feedback" with class "successPageText" 
- [x] Add a div called "SuccessPageBtn"
    - [x] Add a continue button with class "continueBtn"
    - [x] Link it to "../project/homePage/home_page.html"  

#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/successPage'
- [x] Rename this file as 'success_page.css'
- [x] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
    - [x] SuccessPageTextDiv
    - [x] successPageText
    - [x] SuccessPageBtn
    - [x] continueBtn
