### ISSUE TITLE
Add Project Home Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#40]
#### Description: 
- Create and design the HTML, CSS and JS for Project Home Page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [x] Create a directory in 'projects' called projectHomePage

#### TODOs HTML
<del>from 'projects/template', copy "template.html" to 'projects/projectHomePage'</del>
- [x] Rename this file as 'project_home_page.html'
- [x] Add div with class "ProjectHomePageTitleDiv"
    - [x] Make this text with class "projectText"
    - [x] Add div with class "ProjectTodoListDiv"
    - [x] Make text with class "projectTodoList"
    - [x] Default to blank
    - [x] make this editable via js
- [x] Add div with class "ProjectLinkDiv"
    - [x] make blank link  "projectBranchLink"
    - [x] Default to blank
    - [x] make this editable via js
- [x] Add div with class "ProjectDetailDiv"
    - [x] Using js Display the details of current_project  
- [x] Add div with class "ProjectBtnsDiv"
    - [x] Add a make log button with class "makeLogBtn"
    - [x] link it to "../addLogPage/add_log_page.html"
    - [x] Add all logs button with class "allLogsBtn"
    - [x] link it to "../monthlyPage/montly_page.html"

#### TODOs CSS
<del>from 'projects/template', copy "template.css" to 'projects/projectHomePage'</del>
- [x] Rename this file as 'project_home_page.css'
- [x] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
     - [x]  ProjectHomePageTitleDiv
     - [x] projectText
     - [x] ProjectTodoListDiv
     - [x] projectTodoList
     - [x] ProjectLinkDiv
     - [x] projectBranchLink
     - [x] ProjectDetailDiv
     - [x] ProjectBtnsDiv
     - [x] makeLogBtn
     - [x] allLogsBtn

#### TODOs Javascript
- [x] in 'projects/projectHomePage', create 'project_home_page.js'
- [x] This page will display the data for project_n from project_data. the project corresponds to current_project which is project_n (all in localStorage)
- [x] If todolist and branch link is not set, make it the fields editable via "doubleclick"
- [x] Once set, set the todolist and branch link field in localStorage Accordingly
- [x] Populate project details from project data
- [x] Create a file called "project_home_page.tests.js" in "project/tests/"
- [x] Add the following tests (create dummy data in localStorage for these tests)
     - [x] Test if editing TODO list works
     - [x] Editing branch link works
     - [x] Project details loads data correctly
