### ISSUE TITLE
Add Day View Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#41]
#### Description: 
- Create and design the HTML, CSS and JS for Day View
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [x] Create a directory in 'projects' called dayPage
- [ ] NOTE: DO NOT CREATE PROGRESS TRACKER, MAKE LOG BOX TAKE ITS SPACE

#### TODOs HTML
- [ ] from 'projects/template', copy "template.html" to 'projects/dayPage'
- [x] Rename this file as 'day_page.html'
- [x] Create a div with class "DayHeaderDiv"
      - [ ] Create Text with class "DayText"
      - [ ] Create toggle with class "Toggle" which goes to week/month view
      - [ ] link week to "../weekPage/week_page.html"
      - [ ] link month to "../monthPage/month_page.html"
      - [ ] Create a plus button which you can add a log
      - [ ] link this button with "../addLogPage/add_log_page.html"  
- [x] Create a div with class "DayCalendarDiv"
    - [x] Create a div with class "DayCalendarTitle"
         - [x] create a list corresponding to minute based logs 
    - [x] Create a div with class "DayCalendarTime"
         - [x] create a list corresponding to minute based logs 
    - IGNORE: Create a div with class "DayCalendarProgress"
         - IGNORE: create a list corresponding to minute based logs 
- [x] Create a div with class "DayBtnsDiv"
    - [x] Create a next day button with class "nextDayBtn"
    - [x] Create Previous day button "prevDayBtn"
 
#### TODOs CSS
- [ ] from 'projects/template', copy "template.css" to 'projects/dayPage'
- [x] Rename this file as 'day_page.css'
- [x] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
     - [ ] DayHeaderDiv
     - [ ] DayText
     - [ ] Toggle
     - [ ] DayCalendarDiv
     - [ ] DayCalendarTitle
     - [ ] DayCalendarTime
     - [ ] DayBtnsDiv
     - [x] nextDayBtn
     - [x] prevDayBtn

#### TODOs Javascript
- [x] in 'projects/dayPage', create 'day_page.js'
- [ ] Display logs based on current_date field from localStorage
- [ ] Add feature that if the user rightclicks on logs, an option to add log will appear which routes them to the add log page
- [ ] in "projects/tests/" create "day_page.tests.js"
- [ ] Create the following tests
    - [ ] Add dummy project data
    - [ ] Test if log is displayed correctly
    - [ ] test if prev button load data correctly
    - [ ] test if next button loads data correctly
