### ISSUE TITLE
Add Monthly Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#42]
#### Description: 
- Create and design the HTML, CSS and JS for Monthly View Page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [ ] Create a directory in 'projects' called "monthlyPage" 

#### TODOs HTML
- [ ] from 'projects/template', copy "template.html" to 'projects/monthPage'
- [ ] Rename this file as 'month_page.html'
- [ ] Create a div with the class "MotnhHeaderDiv"
     - [ ] Create Text with class "MonthText"
     - [ ] Create toggle with class "Toggle" which goes to week/month view
     - [ ] link week to "../weekPage/week_page.html"
     - [ ] link month to "../monthPage/month_page.html"
     - [ ] Create a plus button to which you can add a log
     - [ ] link this button with "../addLogPage/add_log_page.html"  
- [ ] Create Div "MonthCalandarDiv"
     - [ ] Design Calandar widget
     - [ ] Link each day object to link to "../dayPage/day_page.html"
     - [ ] We'll set how the day information via javascript
- [ ] Create Div "MonthBtns"
    - [ ] Create a next Month button with class "nextMonthBtn"
    - [ ] Create Previous Month button "prevMonthBtn"
 
#### TODOs CSS
- [ ] from 'projects/template', copy "template.css" to 'projects/monthPage'
- [ ] Rename this file as 'month_page.css'
- [ ] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
    - [ ] MonthHeaderDiv
    - [ ] MonthText
    - [ ] MonthCalandarDiv
    - [ ] MonthBtns
    - [ ] nextMonthBtn
    - [ ] prevMonthBtn

#### TODOs Javascript
- [ ] in 'projects/monthPage', create 'month_page.js'
- [ ] Write javascript to go back and forth for months
- [ ] When a user clicks on a date, set the current_date in localStorage to the corresponding date and route them to the link
- [ ] Create "month_page.tests.js" in "projects/tests" and write the following tests
    - [ ]  Test and back forth functionality for calendar widget
    - [ ] Test if current_date is loaded correctly
