### ISSUE TITLE
Add Weekly View Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#43]
#### Description: 
- Create and design the HTML, CSS and JS for Weekly View Page
- Use [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf) for the design
- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```
#### First step:
- [x] Create a directory in 'projects' called "weekPage"

#### TODOs HTML
- [x] from 'projects/template', copy "template.html" to 'projects/weekPage'
- [x] Rename this file as 'week_page.html'
- [x] Create a div with the class "WeekHeaderDiv"
    - [x] Create Text with class "WeekText"
    - [x] Create toggle with class "Toggle" which goes to week/month view
    - [x] link week to "../weekPage/week_page.html"
    - [x] link month to "../monthPage/month_page.html"
    - [x] Create a plus button to which you can add a log
    - [x] link this button with "../addLogPage/add_log_page.html"  
- [x] Create Div "WeekCalandarDiv"
    - [x] Design Calandar widget
    - [x] Link each day object to link to "../dayPage/day_page.html"
    - [x] We'll set how the day information via javascript
- [x] Create Div "WeekBtns"
    - [x] Create a next Month button with class "nextWeekBtn"
    - [x] Create Previous Month button "prevWeekBtn"
 
#### TODOs CSS
- [x] from 'projects/template', copy "template.css" to 'projects/weekPage'
- [x] Rename this file as 'week_page.css'
- [x] Design the following according to the [miro-board](https://github.com/cse110-sp24-group15/cse110-sp24-group15/blob/main/specs/pitch/miro_design_updated.pdf)
    - [x] WeekHeaderDiv
    - [x] WeekText
    - [x] WeekCalandarDiv
    - [x] WeekBtns
    - [x] nextWeekBtn
    - [x] prevWeekBtn

#### TODOs Javascript
- [x] in 'projects/weekPage', create 'week_page.js'
- [x] Write javascript to go back and forth for weeks
- [x] When a user clicks on a date, set the current_date in localStorage to the corresponding date and route them to the link
- [ ] Create "month_page.tests.js" in "projects/tests" and write the following tests
    - [x]  Test and back forth functionality for calendar widget
    - [ ] Test if current_date is loaded correctly
