### ISSUE TITLE
Add Code Mirror to Add Log Page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#72]
## Add Code Mirror Feature

- NOTE: all the project data will be stored in the localStorage as a JSON string with the following format:

```
{ 
current_project: project_n, 
current_date: MM/DD/YYYY
project_data: {
     project_1: {
          projectName: Name, 
          projectTag: Tag, 
          projectContributors: contributors, 
          projectDescription: Description, 
          active: true/false,
          logs: {log_1: {data: BLANK, time: HH:MM, day: DD, Month: MM, Year: YYYY, title: TEXT, contributors: Text}, ...}, 
          BranchLink: link,
          TodoList: {task1: description}
     project_2: ... }
}
```

## TODOs
- [x] Go to the Add Log Page
- [x] Below the description, add a new field which allows you to add a code snippet
- [x] Using [https://codemirror.net/](https://codemirror.net/) add a feature where code snippter field acts like an IDE
- [x] Save this is info to local storgae
