### ISSUE TITLE
Fix Communication Between add_log page, week page and day page

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/cse110-sp24-group15#83]
## TODOs
- [ ] Make sure the day, week and add log page work on the same local storage
- [ ] pre-load a dummy project local storage
- [ ] make log
- [ ] make sure the log shows up on the day view page
   - [ ] show the time when submitted
   - [ ] show the contributors and add visual for the progress
   - [ ] make sure when you hover, a code snippet will appear
- [ ] make sure the log shows up on the week view page
   - [ ] only show time and title of submission
